// <auto-generated />
using System;
using GestaoDeNaoConformidades.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GestaoDeNaoConformidades.Migrations
{
    [DbContext(typeof(GestaoNaoConformidadesDbContext))]
    [Migration("20200428010352_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GestaoDeNaoConformidades.Domain.Entities.Departamento", b =>
                {
                    b.Property<long>("DepartamentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("DepartamentoID");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("GestaoDeNaoConformidades.Domain.Entities.NaoConformidade", b =>
                {
                    b.Property<long>("NaoConformidadeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasKey("NaoConformidadeID");

                    b.ToTable("NaoConformidade");
                });

            modelBuilder.Entity("GestaoDeNaoConformidades.Domain.Entities.NaoConformidadeDepartamento", b =>
                {
                    b.Property<long>("NaoConformidadeID")
                        .HasColumnType("bigint");

                    b.Property<long>("DepartamentoID")
                        .HasColumnType("bigint");

                    b.HasKey("NaoConformidadeID", "DepartamentoID");

                    b.HasIndex("DepartamentoID");

                    b.ToTable("NaoConformidadeDepartamento");
                });

            modelBuilder.Entity("GestaoDeNaoConformidades.Domain.Entities.NaoConformidadeDepartamento", b =>
                {
                    b.HasOne("GestaoDeNaoConformidades.Domain.Entities.Departamento", "Departamento")
                        .WithMany("NaoConformidadeDepartamentos")
                        .HasForeignKey("DepartamentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoDeNaoConformidades.Domain.Entities.NaoConformidade", "NaoConformidade")
                        .WithMany("NaoConformidadeDepartamentos")
                        .HasForeignKey("NaoConformidadeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
